
nhl_players = {'Eastern Conference': {'atlantic_teams': {'Boston Bruins': ['Bergeron', 'Pastrnak', 'Marchand', 'McAvoy', 'Rask'],
                                                        'Buffalo Sabres': ['Eichel', 'Hall', 'Dahlin', 'Olofsson', 'Ullmark'],
                                                        'Detroit Red Wings': ['Larkin', 'Bertuzzi', 'Zadina', 'Bernier', 'Suter'],
                                                        'Florida Panthers': ['Barkov', 'Huberdeau', 'Bobrovsky', 'Ekblad', 'Bennett'],
                                                        'Montreal Canadiens': ['Price', 'Weber', 'Morgan Rielly'],
                                                        'Toronto Maple Leafs': ['Matthews', 'Marner', 'Tavares', 'Rielly', 'Andersen']},
                                      'metropolitan_teams': {'Carolina Hurricanes': ['Aho', 'Svechnikov', 'Teravainen', 'Slavin', 'Nedeljkovic'],
                                                            'Columbus Blue Jackets': ['Jones', 'Werenski', 'Atkinson', 'Dubois', 'Merzlikins'],
                                                            'New Jersey Devils': ['Hughes', 'Hischier', 'Palmieri', 'Subban', 'Blackwood'],
                                                            'New York Islanders': ['Barzal', 'Lee', 'Eberle', 'Pulock', 'Varlamov'],
                                                            'New York Rangers': ['Panarin', 'Zibanejad', 'Kreider', 'Fox', 'Shesterkin'],
                                                            'Philadelphia Flyers': ['Giroux', 'Couturier', 'Voracek', 'Provorov', 'Hart'],
                                                            'Pittsburgh Penguins': ['Crosby', 'Malkin', 'Letang', 'Guentzel', 'Jarry'],
                                                            'Washington Capitals': ['Ovechkin', 'Backstrom', 'Carlson', 'Wilson', 'Samsonov']}},
             'Western Conference': {'central_teams': {'Chicago Blackhawks': ['Kane', 'Toews', 'DeBrincat', 'Keith', 'Lankinen'],
                                                      'Colorado Avalanche': ['MacKinnon', 'Rantanen', 'Landeskog', 'Makar', 'Grubauer'],
                                                      'Dallas Stars': ['Benn', 'Seguin', 'Radulov', 'Heiskanen', 'Bishop'],
                                                      'Minnesota Wild': ['Kaprizov', 'Zuccarello', 'Fiala', 'Suter', 'Talbot'],
                                                      'Nashville Predators': ['Forsberg', 'Johansen', 'Arvidsson', 'Jos', 'Rinne'],
                                                      'St. Louis Blues': ['Tarasenko', 'O\'Reilly', 'Perron', 'Krug', 'Binnington'],
                                                      'Winnipeg Jets': ['Scheifele', 'Wheeler', 'Connor', 'Morrissey', 'Hellebuyck']},
                                  'pacific_teams': {'Anaheim Ducks': ['Getzlaf', 'Lindholm', 'Silfverberg', 'Fowler', 'Gibson'],
                                                    'Calgary Flames': ['Gaudreau', 'Monahan', 'Tkachuk', 'Giordano', 'Markstrom'],
                                                    'Edmonton Oilers': ['McDavid', 'Draisaitl', 'Nugent-Hopkins', 'Barrie', 'Koskinen'],
                                                    'Los Angeles Kings': ['Kopitar', 'Brown', 'Doughty', 'Quick', 'Vilardi'],
                                                    'San Jose Sharks': ['Couture', 'Kane', 'Hertl', 'Karlsson', 'Jones'],
                                                    'Seattle Kraken': ['Tanev', 'McCann', 'Gourde', 'Giordano', 'Grubauer']}}}